### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by parikshitjuvekar** [MMRIZE/MMM-CalendarExt3Timeline#1]
Is there a ready CSS configuration available for the parent MMM-CalendarExt3 module that matches the color scheme of the screenshots in the MMM-CalendarExt3Timeline module?

**Comment by eouia** [comment]
Sorry to late reply. I missed this question.
There is no ready-made CSS. The color scheme is set by your assignment of color for default calendar module.  But you can redeclare the style in your custom.css.
