### ISSUE TITLE
Logic for eventFilter and eventTransformer missing?

### ISSUE THREAD

**Issue by dennis-slozak** [MMRIZE/MMM-CalendarExt3Timeline#2]
I used the example in the readme to exclude full day events from the timeline, however they continue to show. Comparing the code to CalendarExt3 there are a few more references to `filter` within CX3's js than there are in CX3T's js.

**Comment by eouia** [comment]
The logic would be located inside of `/CX3_shared.mjs`. 
https://github.com/MMRIZE/MMM-CalendarExt3Timeline/blob/90fe3ac376d0e1c7ef870bd9e9064f0f811a0341/CX3_shared.mjs#L41-L51
I'm planning to refactor all CX3 suites logic to depend on only 1 shared module, But not done all at this moment. In future, CX3 and CX3A will be changed to use the same logic file.

**Comment by dennis-slozak** [comment]
Thanks for pointing that out. Am I missing something in my config then?

```
config: {
  eventFilter: (ev) => {
    if (ev.isFullday) return false
    return true
  },
  ..
```

**Comment by eouia** [comment]
Let me see. I’ll check.

**Comment by eouia** [comment]
Sorry, It was my mistake. There is some logical bug to handle eventFilter. I'll fix it.

**Comment by dennis-slozak** [comment]
Glad to hear I'm not insane. I'll happily test it on my mirror once any changes are pushed up. Keep me posted!

**Comment by eouia** [comment]
new update for #3

**Comment by dennis-slozak** [comment]
Confirmed to now be filtered out on my deployment. Nicely done!
